spring:
  application:
    name: blog
  datasource:
    url: jdbc:postgresql://${HOST}:${DB_PORT}/${DB_NAME}
    username: ${USERNAME}
    password: ${PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  profiles:
    active: ${PROFILE}
server:
  port: ${SERVER_PORT}
  servlet:
    context-path: /api/v1
springdoc:
  api-docs:
    path: /api-json
  swagger-ui:
    path: /api-docs
