spring:
  profiles:
    active: ${PROFILE:dev} # perfil activo, por defecto "dev"

server:
  port: ${SERVER_PORT:8080} # puerto por defecto 8080
  servlet:
    context-path: /api/v1 # ruta base

springdoc:
  api-docs:
    path: /api-json
  swagger-ui:
    path: /api-docs
